###############################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: pr checks

on:
  pull_request:
    paths:
      - src/**
      - yarn.lock
      - package.json

  workflow_dispatch:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get latest git tag
        id: git-tag-latest
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Remove tag 'v' prefix
        run: echo "GIT_VERSION=$(echo ${{ steps.git-tag-latest.outputs.tag }} | cut -c2-)" >> $GITHUB_ENV

      - name: Get npm version
        id: npm-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1

      - name: Output versions
        run: |
          echo git ${{ env.GIT_VERSION }}
          echo npm ${{ steps.npm-version.outputs.current-version }}

      - name: Get release commit messages
        id: release-commit
        run: |
          RELEASE_COMMIT_MESSAGE=$(git log --grep="Release-As: " -1 --pretty=format:"%s")
          echo "RELEASE_COMMIT_MESSAGE=$RELEASE_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Check if tag already exists and not then check release commit is as expected
        run: |
          if [[ "${{ env.GIT_VERSION }}" == "${{ steps.npm-version.outputs.current-version }}" ]]; then
            echo "Versions match. Proceed to next step"
          else
            echo "Versions do not match. Checking if tag exists."
            tag_exists=$(git tag -l "v${{ steps.npm-version.outputs.current-version }}")
            if [[ -n "$tag_exists" ]]; then
              echo "Package with ${{steps.npm-version.outputs.current-version}} version already exist. "
              exit 1
            else
              echo "Tag does not exist. Checking release commit message."
              if [[ "${{ env.RELEASE_COMMIT_MESSAGE }}" != *"chore: release ${{ steps.npm-version.outputs.current-version }}"* ]]; then
                echo "Expected commit message not found. Please run below command: "
                echo 'git commit --allow-empty -m "chore: release ${{ steps.npm-version.outputs.current-version }}" -m "Release-As: ${{ steps.npm-version.outputs.current-version }}"'
                exit 1
              fi
            fi        
          fi

      - name: Install Dependencies
        run: yarn

      - name: Prettier Checks
        run: yarn pretty:check

      - name: Linter Checks
        run: yarn lint

      - name: Unit Tests
        run: CI=true yarn test

      - name: Build Library
        run: yarn build
